### PR TITLE
small optimization (untested)

### PR DESCRIPTION
**Pull request by inklesspen1rus**

### CODE REVIEW

**Comment by inklesspen1rus** [comment]
oops, do not merge, I should fix one mistake

**Comment by inklesspen1rus** [comment]
Merge

**Comment by rcon420** [comment]
//// zombie_escape-premium.sp
//
// ze-premium/ze-timers.sp(372) : error 017: undefined symbol "client"
// ze-premium/ze-menus.sp(621) : error 017: undefined symbol "sstrcmpzItem"
// ze-premium/ze-keyvalues.sp(242) : warning 204: symbol is assigned a value that is never used: "zmHeath"
// ze-premium/ze-keyvalues.sp(299) : error 017: undefined symbol "GetNum"
// ze-premium/ze-keyvalues.sp(329) : error 088: cannot return a value from a void function
// ze-premium/ze-keyvalues.sp(329) : warning 213: tag mismatch (expected "void", got "Action")
// ze-premium/ze-keyvalues.sp(332) : error 088: cannot return a value from a void function
// ze-premium/ze-keyvalues.sp(332) : warning 213: tag mismatch (expected "void", got "Action")
// ze-premium/ze-keyvalues.sp(347) : warning 209: function "ShowPrimaryWeapons" should return a value
// ze-premium/ze-keyvalues.sp(425) : warning 213: tag mismatch (expected "bool", got "int")

Hey snice author isnt updating his release i tought i could try out your fork there are some errors.  cannot get the plugin working

**Comment by inklesspen1rus** [comment]
@oligarhs420
Oh I forget to compile last commit. I'll fix it in 30 minutes
remember: my fork is untested so if u have bugs please post issue in my fork 

What is version of your compiler and includes?

**Comment by rcon420** [comment]
Compiled with 1.10 without issues. Thank you for the update I will report back if I encounter problems.

**Comment by rcon420** [comment]
I have a few suggestions what you might be interested in to add in your edit because seems like the author has no interest in project no longer.

1. Support for this entwatch plugin - https://github.com/darkerz7/CSGO-Plugins/tree/master/EntWatch_DZ
2. Cvar to disable a hud with information about -  CHOSEN GUN:  (ze-timers.sp line 80)
3. improve gun menu. What I mean it should issue guns on choosing. In sniper007 version you choose guns then you need to press 1 more button to get guns. Not sure but I think Sniper007 gun menu doesn't save your selections after server rr or map change.
4. cvar to define sm_shop command. !shop is way to commonly used command in different plugins or change line 69 in zombie_escape_premium.sp and call it sm_zshop
5.  description about class special powers under  Human & Zombie Class  name  in class menu
6. Ability to define with cvar Ultimate power button 
7. Cooldown for Reloading sound effect. Some players might reload 1 bullet all the time to spam sound effect from reloading.
8. vote option to select a !leader
9. Option to issue grenades set for all classes?  (example I put in cfg that I want that all classes receive weapon_molotov every round.

**Comment by inklesspen1rus** [comment]
> I have a few suggestions what you might be interested in to add in your edit because seems like the author has no interest in project no longer.
> 
> 1. Support for this entwatch plugin - https://github.com/darkerz7/CSGO-Plugins/tree/master/EntWatch_DZ
> 2. Cvar to disable a hud with information about -  CHOSEN GUN:  (ze-timers.sp line 80)
> 3. improve gun menu. What I mean it should issue guns on choosing. In sniper007 version you choose guns then you need to press 1 more button to get guns. Not sure but I think Sniper007 gun menu doesn't save your selections after server rr or map change.
> 4. cvar to define sm_shop command. !shop is way to commonly used command in different plugins or change line 69 in zombie_escape_premium.sp and call it sm_zshop
> 5. description about class special powers under  Human & Zombie Class  name  in class menu
> 6. Ability to define with cvar Ultimate power button
> 7. Cooldown for Reloading sound effect. Some players might reload 1 bullet all the time to spam sound effect from reloading.
> 8. vote option to select a !leader
> 9. Option to issue grenades set for all classes?  (example I put in cfg that I want that all classes receive weapon_molotov every round.

I can't test that I doing but I like coding something like this.
I'll be happy if you will test this plugin and report issues.
Also I made some requests (1, 2(just cutted code), 4(replaced to sm_zshop), 7 and 9)

**Comment by rcon420** [comment]
Sorry I didn't have a  time faster to try out your version there are many errors 
I will start with Error log I get such errors as 

L 08/21/2020 - 04:27:17: [SM] Blaming: zombie_escape-premium.smx::SoundHoo
k
L 08/21/2020 - 13:06:04: [SM]   [5838] Line 781, ze-premium/ze-stocks.sp::GivePlayerNade
L 08/21/2020 - 13:06:04: [SM]   [5839] Line 785, ze-premium/ze-stocks.sp::GivePlayerItem2
L 08/21/2020 - 13:06:04: [SM]   [5840] Line 781, ze-premium/ze-stocks.sp::GivePlayerNade
L 08/21/2020 - 13:06:04: [SM]   [5841] Line 785, ze-premium/ze-stocks.sp::GivePlayerItem2
L 08/21/2020 - 13:06:04: [SM]   [5842] Line 781, ze-premium/ze-stocks.sp::GivePlayerNade
L 08/21/2020 - 13:06:04: [SM]   [5843] Line 785, ze-premium/ze-stocks.sp::GivePlayerItem2
L 08/21/2020 - 13:06:04: [SM]   [5844] Line 781, ze-premium/ze-stocks.sp::GivePlayerNade
L 08/21/2020 - 13:06:04: [SM]   [5845] Line 785, ze-premium/ze-stocks.sp::GivePlayerItem2
 
L 08/21/2020 - 13:28:09: [SM] Blaming: premium\zombie_escape-premium.smx
L 08/21/2020 - 13:28:09: [SM] Call stack trace:
L 08/21/2020 - 13:28:09: [SM]   [1] Line 33, ze-premium/ze-downloads.sp::ReadFileFolder
L 08/21/2020 - 13:28:09: [SM]   [2] Line 37, ze-premium/ze-downloads.sp::ReadFileFolder
L 08/21/2020 - 13:28:09: [SM]   [3] Line 37, ze-premium/ze-downloads.sp::ReadFileFolder
L 08/21/2020 - 13:28:09: [SM]   [4] Line 37, ze-premium/ze-downloads.sp::ReadFileFolder
L 08/21/2020 - 13:28:09: [SM]   [5] Line 37, ze-premium/ze-downloads.sp::ReadFileFolder
L 08/21/2020 - 13:28:09: [SM]   [6] Line 37, ze-premium/ze-downloads.sp::ReadFileFolder
L 08/21/2020 - 13:28:09: [SM]   [7] Line 37, ze-premium/ze-downloads.sp::ReadFileFolder
L 08/21/2020 - 13:28:09: [SM]   [8] Line 11, ze-premium/ze-downloads.sp::DownloadFiles
L 08/21/2020 - 13:28:09: [SM]   [9] Line 156, /home/inklesspen/Документы/GitHub/Zombie-Escape-Premium/addons/sourcemod/scripting/zombie_escape-premium.sp::OnMapStart
 
 
L 08/21/2020 - 13:27:53: [SM] Call stack trace:
L 08/21/2020 - 13:27:53: [SM]   [0] CS_RespawnPlayer
L 08/21/2020 - 13:27:53: [SM]   [1] Line 175, ze-premium/ze-timers.sp::Respawn
L 08/21/2020 - 13:27:53: [SM] Exception reported: Not enough space on the stack
L 08/21/2020 - 13:27:53: [SM] Blaming: premium\zombie_escape-premium.smx
L 08/21/2020 - 13:27:53: [SM] Call stack trace:
L 08/21/2020 - 13:27:53: [SM]   [0] CS_RespawnPlayer
L 08/21/2020 - 13:27:53: [SM]   [1] Line 175, ze-premium/ze-timers.sp::Respawn
L 08/21/2020 - 13:27:53: [SM] Exception reported: Not enough space on the heap
L 08/21/2020 - 13:27:53: [SM] Blaming: premium\zombie_escape-premium.smx
 
L 08/21/2020 - 13:27:53: [SM]   [6358] Line 73, ze-premium/ze-keyvalues.sp::ApplyPlayerHumanClass
L 08/21/2020 - 13:27:53: [SM]   [6359] Line 32, ze-premium/ze-keyvalues.sp::SetPlayerAsHuman
L 08/21/2020 - 13:27:53: [SM]   [6360] Line 93, ze-premium/ze-events.sp::Event_Spawn


What I saw in the game. You can't choose a gun it drops on the ground and u can't pick it up.

You can kill everyone before zombie selection including teammates

Zombies get Glocks 

announcements for selected zombie are gone 

Default player models are gone 


gotv bot spawns in the game


IF u want to test it out on my server contact with me on discord or give information on how I can reach you out 

ooF#7227

**Pull request closed without merging**
